spring.application.name=Asynchronous-Processing
server.port=8080
spring.mvc.servlet.path=/api/

# custom thread pool
thread-pool.corePoolSize = 2
thread-pool.maxPoolSize = 4
thread-pool.queueCapacity = 6
thread-pool.threadNamePrefix = custom-thread-pool-task