spring:
  application:
    name: API-Design-Q1

  datasource:
    url: jdbc:mysql://localhost:3306/60_days_challenge
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    #    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    servlet:
      path: /api/
